
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gorzrufctavjgcrqsukn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcnpydWZjdGF2amdjcnFzdWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzczNzYsImV4cCI6MjA1NzE1MzM3Nn0.BbNaCnrzZnl60uxBbRzEbBmHwUh5FQ6aX8He5-Zgwko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
